name = "colivetree-blog"
type = "webpack"
account_id = "35227d031ca194448383a78c163fc097"
route = ""
zone_id = "0b2ba933c3655ea538f2489518409d76"

[env.staging]
workers_dev = true

[env.production]
workers_dev = false
route = "colivetree.com/*"

[dev]
port=9000
ip="127.0.0.1"

[site]
bucket = "./public"
entry-point = "workers-site"


